version: '2'

services:
  rabbit:
    stdin_open: true
    tty: true
    hostname: "rabbit"
    image: rabbitmq:3-management
    environment:
      RABBITMQ_DEFAULT_USER: "user"
      RABBITMQ_DEFAULT_PASS: "password"
    ports:
      - "5672:5672"

  db:
    stdin_open: true
    tty: true
    image: postgres

  web:
    stdin_open: true
    tty: true
    build: .
    # command: bash -c "cd src/backend && python manage.py migrate && celery multy worker -A perliteio  --loglevel=info && python manage.py runserver 0.0.0.0:8000"
    environment:
      - EXECUTOR=Celery
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
      - rabbit