version: '2'

services:
  rabbit:
    stdin_open: true
    tty: true
    hostname: "rabbit"
    image: rabbitmq:3-management
    environment:
      RABBITMQ_DEFAULT_USER: "user"
      RABBITMQ_DEFAULT_PASS: "password"
    ports:
      - "5672:5672"

  db:
    stdin_open: true
    tty: true
    image: postgres

  web:
    stdin_open: true
    tty: true
    build: .
    # command: python src/backend/manage.py migrate && celery -A src/backend/perliteio worker --loglevel=info
    environment:
      - EXECUTOR=Celery
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
      - rabbit