# Generated by Django 2.0.5 on 2018-09-07 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_auto_20180907_1333'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='born',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='created',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
