# Generated by Django 2.0.5 on 2018-09-07 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_auto_20180907_1338'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='age',
            field=models.IntegerField(default=-1),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='prize',
            field=models.IntegerField(default=-1),
        ),
    ]
